version: '3.8'

volumes:
  postgres_volume:

services:
  db:
    image: postgres:14-alpine3.15
    environment:
      - "POSTGRES_DB=${DB_NAME}"
      - "POSTGRES_USER=${DB_USER}"
      - "POSTGRES_PASSWORD=${DB_PASSWORD}"
    ports:
      - "22222:5432"
    volumes:
      - postgres_volume:/var/lib/postgresql/data_prod

  db_test:
    image: postgres:14-alpine3.15
    environment:
      - "POSTGRES_DB=${DB_NAME_STG}"
      - "POSTGRES_USER=${DB_USER_STG}"
      - "POSTGRES_PASSWORD=${DB_PASSWORD_STG}"
    ports:
      - "22221:5432"
    volumes:
      - postgres_volume:/var/lib/postgresql/data_stg